### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by asgharkhare2016** [F43nd1r/acra-backend#1]
would you please provide an installation guide for this backend?

**Comment by F43nd1r** [comment]
This is currently in an early stage of development, but if you want to try it:

1. checkout the repository
2.  run `gradlew build` on the top level
3. deploy the generated `acra.war` to your java server (e.g. tomcat)

Or for local testing
2. run `gradlew bootRun`

**Comment by F43nd1r** [comment]
@asgharkhare2016 if you do try it out, I'd appreciate feedback on missing features etc.

**Comment by F43nd1r** [comment]
setup guide is now available in the wiki
