### ISSUE TITLE
MySQL ONLY_FULL_GROUP_BY stops statistics page from working

### ISSUE THREAD

**Issue by mikedawson** [F43nd1r/acra-backend#2]
Hi,

I love having a Java based ACRA backend! Many many thanks for this. I just installed this on a new Ubuntu instance running MySQL 5.7 . Apparently in MySQL 5.7  ONLY_FULL_GROUP_BY is enabled by default. When accessing the statistics page, the page wouldn't show and I saw an error like this in the logs:

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'acra.report0_.date' which is not functionally dependent on columns in
 GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

When I changed the sql_mode to remove ONLY_FULL_GROUP_BY - it seemed to work happily again. Perhaps it's possible to set MySQL accordingly by default?

Thanks/regards,

-Mike

**Comment by F43nd1r** [comment]
As this was the only query in the application which did not conform to that policy, I adjusted the query.
